services:
  - type: web
    name: gta-2d
    env: node
    region: frankfurt
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
